### PR TITLE
Xieon patch 1depandabot

### PR DESCRIPTION
**Pull request by Xieon**
## Summary by CodeRabbit

- **New Features**
	- Introduced a Dependabot workflow for automated management of npm package dependencies.
	- Implemented a caching mechanism to optimize the build process by reducing dependency installation time.

- **Improvements**
	- Enhanced efficiency in CI/CD processes with improved cache management options.

### CODE REVIEW

**Comment by Xieon** [comment]
It should now autonmatically merge as soon as it meets the threshold for reviews qwhich is `1

**Review by RichXGC95 — APPROVED** [review]

**Comment by Xieon** [comment]
image

**Comment by Xieon** [comment]
Its something I need to change/figure out - it has to do when there's multiple commits all being pushed at once - 

It will ground them into sets of 5 right now -

**Review by Xieon — COMMENTED** [review]
Should be good

**Comment by Xieon** [comment]
image

**Comment by Xieon** [comment]
@CodeRabbit RErun checkcs

**Comment by Xieon** [comment]
new pull needed

**Pull request closed without merging**
